"""Patent Certificate extractor — the granted-patent certificate issued by the IPO.

Highest-demand unserved source in the library: 63 `autofill.sources[]` entries
across the 34 definitions cite `patent_certificate`, concentrated in the
post-grant forms (renewal, working statements, assignments, restoration).

Keys served, and where the demand comes from:
    patent.number    (22)  every post-grant form's header
    patentee.name    (22)  the party named on the certificate
    patent.grantDate (15)  drives renewal and working-statement due dates
    applicant.name    (3)  see ALIASES below
    invention.title   (1)

The certificate is the most reliably parsed document we handle: it is machine-
generated by the IPO to a fixed template, so confidences run higher than for
the free-text documents.
"""

from __future__ import annotations

from extractors.base import PatternExtractor


class PatentCertificateExtractor(PatternExtractor):
    """Extracts structured facts from an IPO patent certificate."""

    EXTRACTOR_VERSION = "patent_certificate@1"
    SOURCE_TYPE = "patent_certificate"

    PATTERNS = [
        (
            "patent.number",
            [
                r"Patent\s+(?:No|Number)\.?\s*[:\-]?\s*([0-9]{4,9})",
                r"Grant\s+No\.?\s*[:\-]?\s*([0-9]{4,9})",
            ],
            0.90,
        ),
        (
            "patentee.name",
            [
                # Both variants require a real separator — a colon/dash, or the
                # column gap of a printed table. Without one, the prose "granted
                # to the patentee for an invention entitled …" matches and the
                # captured "value" is the rest of the sentence.
                r"Patentee\s*(?:\(s\))?\s*(?:Name)?\s*[:\-]\s*([^\n\r]{3,150})",
                r"(?:^|\n)\s*Patentee\s*(?:\(s\))?[ \t]{2,}([^\n\r]{3,150})",
                r"granted\s+to\s+(?!the\s+patentee\b)([^\n\r]{3,150}?)\s+for\s+an\s+invention",
            ],
            0.85,
        ),
        (
            "patent.grantDate",
            [
                r"Date\s+of\s+Grant\s*[:\-]?\s*([^\n\r]{6,40})",
                r"Date\s+of\s+(?:the\s+)?Grant\s+of\s+(?:the\s+)?Patent\s*[:\-]?\s*([^\n\r]{6,40})",
                r"granted\s+on\s*[:\-]?\s*([^\n\r]{6,40})",
            ],
            0.85,
        ),
        (
            "invention.title",
            [
                r"invention\s+entitled\s*[\"'“‘]?\s*([^\"'”’\n\r]{5,200})",
                r"Title\s+of\s+(?:the\s+)?Invention\s*[:\-]\s*([^\n\r]{5,200})",
            ],
            0.85,
        ),
        (
            "applicant.name",
            [
                r"Applicant\s*(?:\(s\))?\s*(?:Name)?\s*[:\-]\s*([^\n\r]{3,150})",
            ],
            0.80,
        ),
    ]

    # A certificate names a patentee, not an applicant — but the patentee at
    # grant is the applicant of record, which is what the three definitions
    # citing patent_certificate/applicant.name are reaching for. Emitted only
    # when no explicit "Applicant:" label was found, and at reduced confidence
    # so the provenance panel shows it ranking below any real applicant source.
    ALIASES = [("patentee.name", "applicant.name", 0.60)]
